# Generated by Django 4.1 on 2022-08-11 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import user.models.profile_image
import user.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('username', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='Email')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('main_image', models.ImageField(blank=True, max_length=1024, null=True, unique=True, upload_to='', verbose_name='Main Image')),
                ('cover', models.ImageField(blank=True, max_length=128, null=True, upload_to=user.models.user.get_file_path, verbose_name='Cover')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('follower_count', models.PositiveIntegerField(default=0, verbose_name='Follower Count')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='Following Count')),
                ('post_count', models.PositiveIntegerField(default=0, verbose_name='Post Count')),
                ('staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Admin')),
                ('follow', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Follow')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Social Media Name')),
                ('url', models.CharField(max_length=128, verbose_name='Social Media Url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL, verbose_name='User Social Media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('image', models.ImageField(blank=True, null=True, upload_to=user.models.profile_image.get_file_path, verbose_name='Image')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('type', models.CharField(choices=[('Register', 'REGISTER'), ('Forget', 'FORGET')], max_length=8, verbose_name='Type')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Code')),
                ('retry', models.PositiveSmallIntegerField(default=0, verbose_name='Retry')),
                ('used', models.BooleanField(default=False, verbose_name='Used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Activation Code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
